USE [master]
GO

/****** Object:  Database [BlogDB]    Script Date: 8/8/2019 12:25:00 PM ******/
CREATE DATABASE [BlogDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlogDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BlogDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlogDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BlogDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BlogDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlogDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlogDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlogDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlogDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlogDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlogDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlogDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BlogDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlogDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlogDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlogDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlogDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlogDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlogDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlogDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlogDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BlogDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlogDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlogDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlogDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlogDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlogDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BlogDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlogDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BlogDB] SET  MULTI_USER 
GO

ALTER DATABASE [BlogDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlogDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlogDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlogDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BlogDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlogDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BlogDB] SET  READ_WRITE 
GO


